apiVersion: v1
kind: Service
metadata:
    name: db
spec:
    ports:
    - port: 3306
    selector:
        app: db

---

apiVersion: v1
kind: Service
metadata:
    name: pma
spec:
    type: NodePort
    ports:
    - nodePort: 30002
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
        app: pma    

---

apiVersion: v1
kind: Service
metadata:
    name: app
spec:
    type: NodePort
    ports:
    - nodePort: 30001
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
        app: app